import "./globals.css";
import { Providers } from './providers';
import { Fonts } from './fonts';

export const metadata = {
  title: "SerenShift",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang='en' className={Fonts.rubik.variable}>
      <body
        className={`antialiased`}
      >
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
