name: Test Frontend Next.js Build
on:
  pull_request:
    branches:
      - main
    paths:
      - "frontend/**"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
      - name: Cache Next.js build
        uses: actions/cache@v4
        id: next-cache
        with:
          path: frontend/.next
          key: next-build-${{ runner.os }}-${{ hashFiles('frontend/package-lock.json') }}
          restore-keys: |
            next-build-${{ runner.os }}-
      - name: Install dependencies
        working-directory: frontend
        run: npm ci
      - name: Build frontend
        working-directory: frontend
        run: npm run build
      - name: Run Linter
        working-directory: frontend
        run: npm run lint
